import ChatKitWidget from "@/components/chatkit/ChatKitWidget";
import type { Metadata } from "next";

import { Inter, Sora } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider/providers";











const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora", 
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Planova",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      
      className={`${sora.variable} ${inter.variable} antialiased scroll-smooth`}
    >
      <body className="flex flex-col" suppressHydrationWarning>
        <Providers>
          {children}
          <ChatKitWidget />
        </Providers>
      </body>
    </html>
  );
}

