import ChatKitWidget from "@/components/chatkit/ChatKitWidget";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Sora } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider/providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora", // Custom CSS variable
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Planova",
  description: "Generated by create next app",
  icons: {
    icon: "/logo1.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      // className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      className={`${sora.variable} ${inter.variable} antialiased scroll-smooth`}
    >
      <body className="flex flex-col" suppressHydrationWarning>
        <Providers>
          {children}
          <ChatKitWidget />
        </Providers>
      </body>
    </html>
  );
}

